name: PR build

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    name: Run build with Maven
    runs-on: eg-default
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          overwrite-settings: false

      - name: Maven Build & Tests
        run: |
          mvn clean install

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: "cdas-coverage-report-${{ github.run_number }}"
          path: target/site/jacoco-aggregate

      - name: Code Coverage Reporter Action
        uses: Flex/code-coverage-reporter-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.CCR_ES_API_KEY }}
          workflow: pr
          single_build: true
          coverage_reporter: jacoco
          ccr_path: target/site/jacoco-aggregate
          ccr_file: jacoco.xml
